#!/usr/bin/perl
# -*- cperl -*-
#
# Add
# $dbname = $ENV{"PGDATABASE"}           if ($ENV{"PGDATABASE"});
# in /usr/share/perl5/Munin/Plugin/Pgsql.pm __connect function
# in order choose the database
# Copyright (C) 2009 Magnus Hagander, Redpill Linpro AB
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.

=head1 NAME

darwin_changes - Plugin to monitor changes made in the Darwin DB.

=head1 CONFIGURATION

Configuration is done through libpq environment variables, for example
PGUSER, PGDATABASE, etc. For more information, see L<Munin::Plugin::Pgsql>.

=head1 SEE ALSO

L<Munin::Plugin::Pgsql>

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=head1 AUTHOR

Magnus Hagander <magnus@hagander.net>, Redpill Linpro AB
Brice Maron <bmaron@naturalsciences.be>

=head1 COPYRIGHT/License.

Copyright (c) 2009 Magnus Hagander, Redpill Linpro AB

All rights reserved. This program is free software; you can
redistribute it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; version 2
dated June, 1991.

=cut

use strict;
use warnings;

use Munin::Plugin::Pgsql;

my $pg = Munin::Plugin::Pgsql->new(
    title  => 'Changes by Day',
    info   => 'Number of Changes by day stacked',
    vlabel => 'Changes',
    category => 'Darwin2',
    defaultdb => 'darwin2',
    graphdraw => 'AREASTACK',
    basequery =>
      "select count(CASE WHEN action = 'update'THEN 1 ELSE null END) as cnt_update,
count(CASE WHEN action = 'insert'THEN 1 ELSE null END) as cnt_insert,
count(CASE WHEN action = 'delete'THEN 1 ELSE null END) as cnt_delete
from darwin2.users_tracking
where modification_date_time > current_date ;",
   configquery => "VALUES
           ('cnt_insert','Number of insert', 'Number of inserted records'),
           ('cnt_update','Number of update', 'Number of updated records'),
           ('cnt_delete','Number of delete', 'Number of deleted records')
          ",
    pivotquery  => 1,
);

$pg->Process();

